In [ ]:
Task 1 - 1 Write a function to compute 5/0 and use try/except to catch the exception

In [1]:
def devideByZero(temp):
    try:
        temp2 = int(temp)/0
    except ZeroDivisionError as err1:
        print("Can not devide by zero, error trace: {}".format(err1))
        return "Can not devide by zero"
    except Exception as err2:
        print("Unknown error message description here {}".format(err2))
        return "Unknown error while deviding"
        
    return temp2

devideByZero(5)

Can not devide by zero, error trace: division by zero


'Can not devide by zero'

In [ ]:

Task 1 - 2 Implement a python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and object is in ["Baseball", "Cricket"]

In [2]:
subject = ["Americans", "Indians"] 
verb = ["Play", "watch"]
object = ["Baseball", "Cricket"]

for k in subject:
    for i in verb:
        print(k + " " + i + " " + object[0])
        print(k + " " + i + " " + object[1])

Americans Play Baseball
Americans Play Cricket
Americans watch Baseball
Americans watch Cricket
Indians Play Baseball
Indians Play Cricket
Indians watch Baseball
Indians watch Cricket


In [ ]:
Task 2: Write a function so that the columns of the output matrix are powers of the input vector. alexandre theophile vandermonde

In [4]:
import numpy as np

def alexandreThrophileVandermonde(inputmat):
    temp = np.ones(inputmat.shape, dtype=np.int8)
    temp2 = temp.cumsum(axis=1)
    print("Input array is: ")
    print(inputmat)
    print("Alexandre Throphile Vandermonde output array is: ")
    print(inputmat ** (temp2-1))

temp = np.array(np.floor(10*np.random.randn(2,3)))

alexandreThrophileVandermonde(temp)

Input array is: 
[[ -3.  13.  15.]
 [-15.  -1.  11.]]
Alexandre Throphile Vandermonde output array is: 
[[  1.  13. 225.]
 [  1.  -1. 121.]]
